apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    dependOn: ticket-manager
  name: ticket-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-manager
  strategy: {}
  template:
    metadata:
      annotations:
        proxy.istio.io/config: |
          holdApplicationUntilProxyStarts: true
        sidecar.istio.io/proxyCPU: "10m"
        sidecar.istio.io/proxyCPULimit: "150m"
        sidecar.istio.io/proxyMemory: "32Mi"
        sidecar.istio.io/proxyMemoryLimit: "2Gi"
        sidecar.istio.io/inject: "true"
      labels:
        app: ticket-manager
    spec:
      initContainers:
      - name: wait-for-onezone
        image: codingcorp-docker.pkg.coding.net/nocalhost/public/nocalhost-wait:latest
        imagePullPolicy: IfNotPresent
        args:
          - "job"
          - "initdata-job"
      containers:
      - name: ticket-manager
        env:
        - name: DB_HOST
          value: mariadb
        - name: DB_PORT
          value : "3306"
        - name: DB_USER
          value: root
        - name: DB_PASSWD
          value: root123
        - name: DB_DATABASE
          value: ticket
        - name: DB_LOGMODE
          value: "true"
        image: roandocker/ticket-manager:latest
        imagePullPolicy: Always
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 10
          tcpSocket:
            port: 8080
          timeoutSeconds: 3
          failureThreshold: 30
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 30
          periodSeconds: 10
          tcpSocket:
            port: 8080
          timeoutSeconds: 3
          failureThreshold: 30
        resources:
          limits:
            cpu: 150m
            memory: 680Mi
          requests:
            cpu: 50m
            memory: 256Mi
      enableServiceLinks: false
---
apiVersion: v1
kind: Service
metadata:
  name: ticket-manager
spec:
  ports:
  - name: "http-8080"
    port: 8080
    targetPort: 8080
  selector:
    app: ticket-manager
  type: ClusterIP
status:
  loadBalancer: {}
...