// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.msa.ticket.frontend.rpc.grpc.user.server;

public final class User {
  private User() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_UserMsgRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_UserMsgRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_UserMsgReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_UserMsgReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\004user\"\037\n\016UserMsgRequest\022\r\n\005" +
      "count\030\001 \001(\005\"\037\n\014UserMsgReply\022\017\n\007message\030\001" +
      " \001(\t2D\n\007UserRPC\0229\n\013GetAllUsers\022\024.user.Us" +
      "erMsgRequest\032\022.user.UserMsgReply\"\000B0\n,co" +
      "m.msa.ticket.frontend.rpc.grpc.user.serv" +
      "erP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_user_UserMsgRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_user_UserMsgRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_UserMsgRequest_descriptor,
        new java.lang.String[] { "Count", });
    internal_static_user_UserMsgReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_user_UserMsgReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_UserMsgReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
