// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.msa.ticket.frontend.rpc.grpc.user.server;

public interface UserMsgRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.UserMsgRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 count = 1;</code>
   * @return The count.
   */
  int getCount();
}
