// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.msa.ticket.frontend.rpc.grpc.user.server;

public interface UserMsgReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.UserMsgReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
