// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: movie.proto

package com.msa.ticket.frontend.rpc.grpc.movie.server;

public interface MovieMsgRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:movie.MovieMsgRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 count = 1;</code>
   * @return The count.
   */
  int getCount();
}
