// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: movie.proto

package com.msa.ticket.frontend.rpc.grpc.movie.server;

public interface MovieMsgReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:movie.MovieMsgReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
