// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: movie.proto

package com.msa.ticket.frontend.rpc.grpc.movie.server;

public final class Movie {
  private Movie() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_movie_MovieMsgRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_movie_MovieMsgRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_movie_MovieMsgReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_movie_MovieMsgReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013movie.proto\022\005movie\" \n\017MovieMsgRequest\022" +
      "\r\n\005count\030\001 \001(\005\" \n\rMovieMsgReply\022\017\n\007messa" +
      "ge\030\001 \001(\t2J\n\010MovieRPC\022>\n\014GetAllMovies\022\026.m" +
      "ovie.MovieMsgRequest\032\024.movie.MovieMsgRep" +
      "ly\"\000B1\n-com.msa.ticket.frontend.rpc.grpc" +
      ".movie.serverP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_movie_MovieMsgRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_movie_MovieMsgRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_movie_MovieMsgRequest_descriptor,
        new java.lang.String[] { "Count", });
    internal_static_movie_MovieMsgReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_movie_MovieMsgReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_movie_MovieMsgReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
